server:
  port: 8083    # ← This forces the service to run ONLY on port mentioned

# Optional but useful settings
Spring:
  Application:
    name: transaction-service

# If you have other configs
transaction-service:
  url: http://localhost:8083

# secret key for jwt token
jwt:
  secret: "PaymentWalletSystemStrongSecretKeyAtLeast64CharsLongAndRandomWithoutUnderScore"

#Disable default security - important
spring:
  security:
    user:
      name: ""      # Disable default user
      password: ""


#Feign Configuration
feign:
  client:
    config:
      user-service:
        connectTimeout: 5000
        readTimeout: 5000

#Wallet Service URL (used when running locally without Eureka)
wallet-service:
  url: http://localhost:8082

notification-service:
  url: http://localhost:8084

#Docker : Spring will automatically pick application-docker.yml
#spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

# ==================== RESILIENCE4J CONFIG ====================
resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuit:
        registerHealthIndicator: true
        slidingWindowSize: 10                  # Last 10 calls are monitored
        failureRateThreshold: 50               # Open circuit if 50% calls fail
        waitDurationInOpenState: 10s           # How long to stay open
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      walletServiceCircuit:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      meTransferCircuit:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      transferCircuit:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      userServiceRetry:
        maxAttempts: 3
        waitDuration: 500ms
      meTransferRetry:
        maxAttempts: 3
        waitDuration: 800ms
      transferRetry:
        maxAttempts: 3
        waitDuration: 800ms


# ====================== ACTUATOR CONFIG ======================
management:
  endpoints:
    web:
      exposure:
        include: "health,info,circuitbreakers,retries"   # Only useful and safe endpoints
  endpoint:
    health:
      show-details: always           # Change to 'when-authorized' in production
    circuitbreakers:
      enabled: true
    retries:
      enabled: true

#Health Check: http://localhost:8083/actuator/health
#Circuit Breakers: http://localhost:8083/actuator/circuitbreakers
#Retries: http://localhost:8083/actuator/retries
#Info: http://localhost:8083/actuator/info