spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: ["*"]
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
            allowedHeaders: ["*"]
            allowCredentials: false
            exposedHeaders: ["Authorization"]

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: root
          uri: lb://user-service
          predicates:
            - Path=/
          filters:
            - RewritePath=/, /swagger-ui/index.html

        - id: swagger
          uri: lb://user-service
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /auth/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}
            - PreserveHostHeader

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets/**
          filters:
            - RewritePath=/api/wallets/(?<segment>.*), /api/wallets/${segment}
            - PreserveHostHeader

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**, /api/transfer/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
            - PreserveHostHeader

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
            - PreserveHostHeader