spring:
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: api-gateway
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}