spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: ["*"]
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
            allowedHeaders: ["*"]
            allowCredentials: false
            exposedHeaders: ["Authorization"]

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: root
          uri: lb://user-service
          predicates:
            - Path=/
          filters:
            - RewritePath=/, /swagger-ui/index.html

        - id: swagger
          uri: lb://user-service
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /auth/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}
            - PreserveHostHeader
            - RateLimitingFilter #If limit exceeded → returns HTTP 429 Too Many Requests

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets/**
          filters:
            - RewritePath=/api/wallets/(?<segment>.*), /api/wallets/${segment}
            - PreserveHostHeader
            - RateLimitingFilter #If limit exceeded → returns HTTP 429 Too Many Requests

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**, /api/transfer/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
            - PreserveHostHeader
            - RateLimitingFilter #If limit exceeded → returns HTTP 429 Too Many Requests

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/(?<segment>.*), /${segment}
            - PreserveHostHeader
            - RateLimitingFilter #If limit exceeded → returns HTTP 429 Too Many Requests

# ====================== ACTUATOR CONFIG ======================
management:
  endpoints:
    web:
      exposure:
        include: "health,info,circuitbreakers,retries"   # Only useful and safe endpoints
  endpoint:
    health:
      show-details: always           # Change to 'when-authorized' in production
    circuitbreakers:
      enabled: true
    retries:
      enabled: true

#Health Check: http://localhost:8080/actuator/health
#Circuit Breakers: http://localhost:8080/actuator/circuitbreakers
#Retries: http://localhost:8080/actuator/retries
#Info: http://localhost:8080/actuator/info

#============= RATE LIMIT =============
resilience4j:
  ratelimiter:
    instances:
      # Global default rate limit (for all unauthenticated calls)
      defaultRateLimit:
        limitForPeriod: 20                  # 20 requests
        limitRefreshPeriod: 1s              # per second
        timeoutDuration: 0ms

      # Per User Rate Limit (after authentication)
      userRateLimit:
        limitForPeriod: 100                 # 100 requests per user
        limitRefreshPeriod: 60s             # per minute
        timeoutDuration: 500ms