server:
  port: 8081      # ← This forces the service to run ONLY on port mentioned

# Optional but useful settings
Spring:
  Application:
    name: user-service

# If you have other configs
user-service:
  url: http://localhost:8081

# secret key for jwt token
jwt:
  secret: "PaymentWalletSystemStrongSecretKeyAtLeast64CharsLongAndRandomWithoutUnderScore"

#Disable default security - important
#spring:
  security:
    user:
      name: ""      # Disable default user
      password: ""

#User Service URL (used when running locally without Eureka)
wallet-service:
  url: http://localhost:8081

#Docker : Spring will automatically pick application-docker.yml
#spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

# ====================== ACTUATOR CONFIG ======================
management:
  endpoints:
    web:
      exposure:
        include: "health,info,circuitbreakers,retries"   # Only useful and safe endpoints
  endpoint:
    health:
      show-details: always           # Change to 'when-authorized' in production
    info:
      access: unrestricted
    circuitbreakers:
      enabled: true
    retries:
      enabled: true

#Health Check: http://localhost:8081/actuator/health
#Circuit Breakers: http://localhost:8081/actuator/circuitbreakers
#Retries: http://localhost:8081/actuator/retries
#Info: http://localhost:8081/actuator/info

info:
  app:
    name: ${spring.application.name}
    spring-boot-version: ${spring-boot.version}
    java-version: ${java.version}
    description: Payment Wallet System - Microservices Architecture
    author: Mavishnu KJ