spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  data:
    redis:
      host: redis          # Important: Use service name as hostname
      port: 6379

server:
  port: 8080             # Internal port inside container
  external:
    port: 8081

#EUREKA RELATED
#spring:
  application:
    name: user-service

eureka:
  instance:
    hostname: localhost
    # Explicitly tell Eureka the external port that browser should use
    instance-id: ${spring.application.name}:${server.external.port:8080}
    prefer-ip-address: false
    home-page-url: http://${eureka.instance.hostname}:${server.external.port:8080}/
    status-page-url: http://${eureka.instance.hostname}:${server.external.port:8080}/actuator/info
    health-check-url: http://${eureka.instance.hostname}:${server.external.port:8080}/actuator/health

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true