spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  data:
    redis:
      host: redis          # Important: Use service name as hostname
      port: 6379

server:
  port: 8080             # Internal port inside container

#EUREKA RELATED
#spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/   # ← Use service name in Docker
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false